#!/usr/bin/env bash
# instll Nginx and host a web page
sudo apt -y update
sudo apt install -y nginx
sudo ufw allow 'nginx HTTP'
sh -c 'echo "Hello World" > /var/www/html/index.html'
sudo service nginx restart
