#!/usr/bin/env bash
# instll Nginx and host a web page
# Configure Nginx server so that /redirect_me is redirecting to another page.
# Configure Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
sudo apt -y update
sudo apt install -y nginx
sudo ufw allow 'nginx HTTP'
sh -c 'echo "Hello World" > /var/www/html/index.html'
sed -i '/listen 80 default_server/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sh -c 'echo "Ceci n'"'"'est pas une page." > /var/www/html/404.html'
sed -i '/listen 80 default_server/a \\terror_page 404 /404.html;' /etc/nginx/sites-available/default
service nginx restart
