#!/usr/bin/env bash
# generate a MySQL dump and creates a compressed archive out of it.
mysqldump --all-databases -u root --password="$1" > backup.sql
file="$(date +"%d")-$(date +"%m")-$(date +"%Y").tar.gz"
tar -czvf "$file" backup.sql
