#!/usr/bin/env bash
# configure nginx to run on port 80
sudo apt-get update
sudo apt-get reinstall -y nginx
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart

