#!/usr/bin/env bash
#this code loops from 1 to 10 and:
#####displays bad luck for the 4th loop iteration
#####displays good luck for the 8th loop iteration
#####displays Best School for the other iterations

iter=0
while [ "$iter" -le 10 ]; do
	if [ "$iter" -eq 4 ]; then
		echo "bad luck"
	elif [ "$iter" -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((iter++))
done
