#!/usr/bin/env bash
#gives you information about the school file.
if [ -e "school" ]; then
	echo "school file exists"
else
	echo "school file does not exist"
	exit 0
fi

if [ ! -s "school" ]; then
	echo "school file is empty"
else
	echo "school file is not empty"
fi

if [ ! -d "school" ]; then
	echo "school is a regular file"
fi
